name: Release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest'
            args: '--target x86_64-apple-darwin'
          - platform: 'ubuntu-22.04'
            args: ''
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          # Pin Node to satisfy Vite (20.19+ or 22.12+)
          node-version: '22.12.0'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            patchelf \
            build-essential \
            libssl-dev \
            file

      - name: Install frontend dependencies
        run: pnpm install --frozen-lockfile

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: 'FM24 Scout App v__VERSION__'
          releaseBody: |
            See the assets to download and install this version.
            
            ## Installation
            
            ### Windows
            - Download `FM24-Scout-App_x64-setup.exe` for the installer
            - Or download `FM24-Scout-App_x64_en-US.msi` for MSI package
            
            ### macOS
            - Download `FM24-Scout-App_x64.dmg` for Intel Macs
            - Download `FM24-Scout-App_aarch64.dmg` for Apple Silicon (M1/M2/M3)
            
            ### Linux
            - Download `fm24-scout-app_amd64.deb` for Debian/Ubuntu
            - Download `fm24-scout-app_amd64.AppImage` for universal Linux
            
            ## What's Changed
            Please see the [CHANGELOG](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md) for details.
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}
